app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
  path: /logout

secure:
  path: /api/register_phone
  defaults: { _controller: AppBundle:API/Api:registerPhone}
  schemes: [https]