# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
      our_db_provider:
        entity:
          class: AppBundle:User
          property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            pattern: ^/
            http_basic: ~
            provider: our_db_provider

            form_login:
              default_target_path: login
              login_path: login
              check_path: login

            logout:
              path:   /logout
              target: /login

            #    pattern: ^/api
            #    stateless: false
            #    simple_preauth:
            #      authenticator: apikey_authenticator
            #    provider: api_key_user_provider


            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html



    access_control:
      - { path: ^/api, roles: [ROLE_ADMIN, ROLE_API] }
      - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/, roles: [ROLE_ADMIN, ROLE_API, ROLE_USER] }

    encoders:
      AppBundle\Entity\User: bcrypt

      Symfony\Component\Security\Core\User\User: plaintext
