# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    api_key_user_provider:
        class: AppBundle\Security\ApiKeyUserProvider

    apikey_authenticator:
        class: AppBundle\Security\ApiKeyAuthenticator
        arguments: ["@security.http_utils"]
        public: false

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

