<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    /**
     * @param Group $group
     * @return array
     */
    public function getUsersInGroup(Group $group) {
        return $this->createQueryBuilder('u')
            ->join('u.groups', 'g')
            ->where('g.id = :groupId')
            ->setParameter('groupId', $group)
            ->getQuery()
            ->getResult();
    }

    public function getUsersInGroupWithId($groupId) {
        return $this->createQueryBuilder('u')
            ->join('u.groups', 'g')
            ->where('g.id = :groupId')
            ->setParameter('groupId', $groupId)
            ->getQuery()
            ->getResult();
    }


}
